package com.xxx.pms.entity;

import lombok.Data;

import javax.persistence.Table;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_task
 */
@Data
@Table(name = "sys_task")
public class Task {

    private Integer id;

    /**
     
     *   所属项目ID
     */
    private Integer projectId;

    /**
     
     *   迭代ID
     */
    private Integer iterative;

    /**
     
     *   创建人用户ID
     */
    private Integer createUserId;

    /**
     
     *   创建人昵称
     */
    private String createUserName;

    /**
     
     *   任务内容
     */
    private String context;

    /**
     
     *   计划开始时间
     */
    private Date gmtPlanStart;

    /**
     
     *   计划结束时间
     */
    private Date gmtPlanEnd;

    /**
     
     *   计划时间分钟数
     */
    private Short planMinute;

    /**
     
     *   创建时间
     */
    private Date gmtCreate;

    /**
     
     *   任务状态-1未完成1完成
     */
    private Byte state;


}